### ISSUE TITLE
../vcflib/src/Variant.h:18:21: fatal error: tabix.hpp: No such file or directory

### ISSUE THREAD

**Issue by drwhitehouse** [freebayes/freebayes#492]
I am attempting to build freebayes 1.2.0 for one of our Bioinformatics researchers.
I'd like to enable a parallel build and the methodology I am using is as follows:

Software versions:

bamtools/2.4.1 
parallel/20170422 
htslib/1.6
cmake/3.8.0
gcc/4.8.5

firstly I clone the freebayes repo using:

`git clone git@github.com:ekg/freebayes.git --branch v1.2.0 --recursive`

then:

`cd freebayes/vcflib`
`make openmp`
`cd .. && make`

At which point the build fails with:

```
g++   -I../src -I../ttmath -I../vcflib/src/ -I../vcflib/smithwaterman/ -I../vcflib/multichoose/ -I../vcflib/filevercmp/ -I../vcflib/fastahack/ -I../SeqLib/htslib -I../SeqLib  -c freebayes.cpp
In file included from AlleleParser.h:31:0,
                 from freebayes.cpp:30:
../vcflib/src/Variant.h:18:21: fatal error: tabix.hpp: No such file or directory
 #include "tabix.hpp"
                     ^
compilation terminated.
```

I am really struggling to understand the build process. 
I understand that I must make vcflib and that seems to work well.
I also understand that I will eventually need gnu parallel to make the freebayes-parallel script work but I cannot seem to get past this point. I have seen that other peoples compilation failed at the same point and they were advised to recursively clone the freebayes repo - but I have done that and it still doesn't seem to work!

To complicate matters slightly I am working on an HPC cluster and we have a fairly complicated custom build process, but for what it is worth things seem to work fine with freebayes version 1.1.0.

I'd be really grateful for any advice or hints about more complete documentation.

**Comment by sbutcher** [comment]
The patches used by bioconda in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/freebayes/build.sh are also required to build without conda. 

```
sed -i.bak 's/SUBDIRS=./SUBDIRS=.\'$'\n''LOBJS=tabix.o/' vcflib/tabixpp/Makefile
sed -i.bak 's/-ltabix//' vcflib/Makefile
```

alternatively I built it by modifying the freebayes Makefile
```
--- a/src/Makefile
+++ b/src/Makefile
@@ -26,7 +26,7 @@ TABIX_ROOT=$(VCFLIB_ROOT)/tabixpp
 HTSLIB_ROOT=$(SEQLIB_ROOT)/htslib
 
 LIBS = -lz -llzma -lbz2 -lm -lpthread
-INCLUDE = -I../src -I../ttmath -I$(VCFLIB_ROOT)/src/ -I$(VCFLIB_ROOT)/smithwaterman/ -I$(VCFLIB_ROOT)/multichoose/ -I$(VCFLIB_ROOT)/filevercmp/ -I$(VCFLIB_ROOT)/fastahack/ -I$(HTSLIB_ROOT) -I$(SEQLIB_ROOT) 
+INCLUDE = -I../src -I../ttmath -I$(VCFLIB_ROOT)/src/  -I$(TABIX_ROOT)/ -I$(VCFLIB_ROOT)/smithwaterman/ -I$(VCFLIB_ROOT)/multichoose/ -I$(VCFLIB_ROOT)/filevercmp/ -I$(VCFLIB_ROOT)/fastahack/ -I$(HTSLIB_ROOT) -I$(SEQLIB_ROOT)  -I$(TABIX_ROOT)/htslib
 #INCLUDE = -I../ttmath -I$(BAMTOOLS_ROOT)/src/ -I$(VCFLIB_ROOT)/src/ -I$(TABIX_ROOT)/ -I$(VCFLIB_ROOT)/smithwaterman/ -I$(VCFLIB_ROOT)/multichoose/ -I$(VCFLIB_ROOT)/filevercmp/ -I$(VCFLIB_ROOT)/fastahack/ -I$(HTSLIB_ROOT) -I$(SEQLIB_ROOT) -I$(SEQLIB_ROOT)/htslib
 
 all: autoversion ../bin/freebayes ../bin/bamleftalign
```

**Comment by stevenweaver** [comment]
I ran into a few issues here as well. The issue was with building vcflib and its missing dependency, tabixpp. 
```
sweaver:build/ cmake ..                                                                                                                                                                                                                         [17:53:58]
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /opt/aocc/AOCC-1.3.0-Compiler/bin/clang
-- Check for working C compiler: /opt/aocc/AOCC-1.3.0-Compiler/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/aocc/AOCC-1.3.0-Compiler/bin/clang++
-- Check for working CXX compiler: /opt/aocc/AOCC-1.3.0-Compiler/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.2.2") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- 

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'htslib'
--   Found htslib, version 1.9
-- Checking for module 'tabixpp'
--   No package 'tabixpp' found
Pandoc needs to be installed to generate the man pages
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sweaver/programming/vg-tutorials/vcflib/build
```

The steps I used to remedy if using a distribution of Linux that doesn't have tabixpp packaged (you could also manipulate environment variables instead of copying the library to `/usr/lib64/`.
```
git clone --recursive git@github.com:ekg/tabixpp.git
make
ranlib tabix.o 
sudo cp tabixpp/libtabixpp.a /usr/lib64/
```

Then attempt to build vcflib as normal. 

Hope this helps.
